####
#### BACKEND - API - DEPLOY
####

staging: # staging is executed for all commits that were pushed to master branch
  stage: deploy
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api_key=$HEROKU_API_KEY
  only:
    - staging

production: # production is executed for all pushed tags.
  stage: deploy
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api_key=$HEROKU_API_KEY
  only:
    - tags
