stages:
  - test
  - build
  - deploy

####
#### BACKEND - API - TEST
####
API:Test:
  stage: test
  image: maven:latest
  script:
    - cd api
    - mvn test -e "-Dspring.datasource.url=$DATASOURCE_URL" "-Dspring.datasource.username=$DATASOURCE_USERNAME" "-Dspring.datasource.password=$DATASOURCE_PASSWORD" "-Dlogging.level.org.springframework=INFO" "-Dlogging.level.com.api.kookie=DEBUG"
  only:
    - staging
    - tags

####
#### BACKEND - API - BUILD
####
API:Build:
  stage: build
  image: maven:latest
  needs:
    - API:Test
  script:
    - cd api
    - mvn clean package -e "-Dspring.datasource.url=$DATASOURCE_URL" "-Dspring.datasource.username=$DATASOURCE_USERNAME" "-Dspring.datasource.password=$DATASOURCE_PASSWORD" "-Dlogging.level.org.springframework=INFO" "-Dlogging.level.com.api.kookie=DEBUG"
  after_script:
    - pwd
    - mv api/target/*.war ./
  artifacts:
    name: "kookie-api-v1.0.3"
    expire_in: 1 week
    paths:
      - "*.war"
  only:
    - tags

####
#### BACKEND - API - DEPLOY STAGING
####
API:Staging: # staging is executed for all commits that were pushed to master branch
  stage: deploy
  needs:
    - API:Test
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api_key=$HEROKU_API_KEY
  only:
    - staging

####
#### BACKEND - API - DEPLOY PRODUCTION
####
API:Production: # production is executed for all pushed tags.
  stage: deploy
  needs:
    - API:Test
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api_key=$HEROKU_API_KEY
  only:
    - tags


####
#### FRONTEND - MOBILE - TEST - ANDROID
####
Android:MobileTest:
  stage: test
  image: cirrusci/flutter
  script:
    - cd mobile/kookie
    - flutter test
  only:
    - staging
    - tags

####
#### FRONTEND - MOBILE - BUILD - ANDROID
####
Android:MobileBuild:
  stage: build
  image: cirrusci/flutter
  needs:
    - Android:MobileTest
  before_script:
    - cd mobile/kookie
    - flutter packages get
    - flutter clean
  script:
    - flutter doctor --android-licenses
    - flutter build apk
  after_script:
    - pwd
    - mv mobile/kookie/build/app/outputs/flutter-apk/*.apk ./
  artifacts:
    name: "kookie-v1.0.3"
    expire_in: 1 day
    paths:
      - "*.apk"
  only:
    - tags
