staging:
  stage: deploy
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=api-cookie-env-staging --api_key=$HEROKU_API_KEY
  only:
    - staging

production:
  stage: deploy
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=api-cookie-env-production --api_key=$HEROKU_API_KEY
  only:
    - master