stages:
  - test
  - build
  - deploy

####
#### BACKEND - API - TEST
####
apiTest:
  stage: test
  image: maven:latest
  script:
    - cd api
    - mvn test "-Dspring.datasource.url=$DATASOURCE_URL" "-Dspring.datasource.username=$DATASOURCE_USERNAME" "-Dspring.datasource.password=$DATASOURCE_PASSWORD"
  only:
    - staging

####
#### BACKEND - API - BUILD
####
apiBuild:
  stage: build
  image: maven:latest
  script:
    - cd api
    - mvn clean package -e "-Dspring.datasource.url=$DATASOURCE_URL" "-Dspring.datasource.username=$DATASOURCE_USERNAME" "-Dspring.datasource.password=$DATASOURCE_PASSWORD"
  artifacts:
    name: "api-snapshot"
    paths:
      - target/*.jar
  only:
    - staging
    
####
#### BACKEND - API - DEPLOY STAGING
####
staging: # staging is executed for all commits that were pushed to master branch
  stage: deploy
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api_key=$HEROKU_API_KEY
  only:
    - staging

####
#### BACKEND - API - DEPLOY PRODUCTION
####
production: # production is executed for all pushed tags.
  stage: deploy
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api_key=$HEROKU_API_KEY
  only:
    - tags