stages:
  - test
  - build
  - deploy

####
#### BACKEND - API - TEST
####
apiTest:
  stage: test
  image: maven:latest
  script:
    - cd api
    - mvn test "-Dspring.datasource.url=$DATASOURCE_URL" "-Dspring.datasource.username=$DATASOURCE_USERNAME" "-Dspring.datasource.password=$DATASOURCE_PASSWORD" "-Dlogging.level.org.springframework=INFO" "-Dlogging.level.com.api.kookie=DEBUG"
  only:
    - staging
    - tags

####
#### BACKEND - API - BUILD
####
apiBuild:
  stage: build
  image: maven:latest
  needs:
    - apiTest
  script:
    - cd api
    - mvn clean package -e "-Dspring.datasource.url=$DATASOURCE_URL" "-Dspring.datasource.username=$DATASOURCE_USERNAME" "-Dspring.datasource.password=$DATASOURCE_PASSWORD" "-Dlogging.level.org.springframework=INFO" "-Dlogging.level.com.api.kookie=DEBUG"
  artifacts:
    name: "api-snapshot"
    expire_in: 1 week
    paths:
      - api/target/*.war
  only:
    - staging
    - tags
    
####
#### BACKEND - API - DEPLOY STAGING
####
staging: # staging is executed for all commits that were pushed to master branch
  stage: deploy
  needs:
    - apiTest
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api_key=$HEROKU_API_KEY
  only:
    - staging

####
#### FRONTEND - MOBILE - TEST - ANDROID
####
Android:mobileTest:
  stage: test
  script:
    - cd mobile/kookie
    -  flutter test
  only:
    - staging
    - tags

####
#### FRONTEND - MOBILE - BUILD - ANDROID
####
Android:mobileBuild:
  stage: build
  needs:
    - Android:mobileTest
  before_script:
    - cd mobile/kookie
    - flutter packages get
    - flutter clean
  script:
    - flutter doctor --android-licenses
    - flutter build apk --flavor production --release
  artifacts:
    paths:
      - "mobile/kookie/**/**/**/**/**/**/*.apk"
    expire_in: 1 day
  only:
    - staging
    - tags
