staging:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=api-cookie-env-staging --api_key=$HEROKU_API_KEY
  only:
    - master

production:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --api-cookie-env-production --api_key=$HEROKU_API_KEY
  only:
    - tags