####
#### BACKEND - API - DEPLOY
####

staging:
  stage: deploy
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api_key=$HEROKU_API_KEY
  only:
    - staging

production:
  stage: deploy
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api_key=$HEROKU_API_KEY
  only:
    - master

####
#### FRONTEND - TEST BUILD THEN DEPLOY
####

stages:
  - test
  - build
  - deploy

####
#### FRONTEND - MOBILE - TEST
####

flutter_test: # Name of the lane
  stage: test # type of stage
  script:
    - cd mobile/kookie
    - flutter test # Run Flutter test
  tags:
    - flutter # Tags for runner

####
#### FRONTEND - MOBILE - BUILD ANDROID
####

flutter_build_android: #Job name
  stage: build # kind of job
  before_script:
    - cd mobile/kookie
    - flutter packages get
    - flutter clean
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  tags:
    - flutter

####
#### FRONTEND - MOBILE - BUILD IOS
####
flutter_build_ios:
  stage: build
  before_script:
    - cd mobile/kookie
    - flutter packages get
    - flutter clean
  script:
    - flutter build ios
    - cd ios
    - xcodebuild clean archive -workspace Runner.xcworkspace -scheme Runner -archivePath RunnerArchive
    - xcodebuild -exportArchive -archivePath RunnerArchive.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./build
  artifacts:
    paths:
      - ios/build/Runner.ipa
  tags:
    - flutter

####
#### FRONTEND - MOBILE - DEPLOY
####

deploy_ios:
  stage: deploy
  dependencies:
    - flutter_build_ios
  script:
    - cd mobile/kookie
    - appcenter login --token $APPCENTER_API_TOKEN
    - appcenter distribute release -f ios/build/Runner.ipa -g Collaborators --app kookie-pai/kookie-app-ios
  tags:
    - flutter

deploy_android:
  stage: deploy
  dependencies:
    - flutter_build_android
  script:
    - cd mobile/kookie
    - appcenter login --token $APPCENTER_API_TOKEN
    - appcenter distribute release -f build/app/outputs/apk/release/app-release.apk -g Collaborators —app kookie-pai/kookie-app-android
  tags:
    - flutter