staging:
  stage: deploy
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api_key=$HEROKU_API_KEY
  only:
    - staging

production:
  stage: deploy
  script:
    - gem install dpl
    - cd api
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api_key=$HEROKU_API_KEY
  only:
    - master